# Generated by Django 4.0.4 on 2023-01-13 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0002_remove_product_created_product_cpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='categories.category'),
        ),
    ]
