# Generated by Django 4.0.4 on 2023-01-13 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='key',
        ),
        migrations.CreateModel(
            name='ProductKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_key', to='products.product')),
            ],
            options={
                'verbose_name': 'Ключ',
                'verbose_name_plural': 'Ключи',
            },
        ),
    ]
